import type { JewelleryDetailProduct } from './JewelleryDetailPage';

export const EARRING_PRODUCTS: Record<string, JewelleryDetailProduct> = {
  'brilliance-studs': {
    name: 'Brilliance Studs',
    subtitle: 'Diamond Stud Earrings',
    basePrice: 3400,
    materials: ['Platinum', '18k White Gold', '18k Yellow Gold'],
    images: ['/images/earrings/earring-1.png', '/images/earrings/earring-3.png', '/images/earrings/earring-5.png'],
    description: 'The Brilliance Studs set the standard for the perfect diamond stud. Two perfectly matched round brilliant-cut diamonds in a classic four-claw platinum setting — the earrings that never leave the ear.',
    diamondMode: 'total-carat',
    caratIsPair: true,
    pricePerCarat: 4200,
  },
  'cascade-drops': {
    name: 'Cascade Drops',
    subtitle: 'Diamond Drop Earrings',
    basePrice: 5800,
    materials: ['Platinum', '18k White Gold'],
    images: ['/images/earrings/earring-2.png', '/images/earrings/earring-6.png', '/images/earrings/earring-4.png'],
    description: 'A graduating line of brilliant-cut diamonds descends from the ear in a fluid cascade. Each stone is individually claw-set for maximum light return and movement.',
    diamondMode: 'total-carat',
    caratIsPair: true,
    pricePerCarat: 3800,
  },
  'soleste-studs': {
    name: 'Soleste Studs',
    subtitle: 'Diamond Halo Stud Earrings',
    basePrice: 4600,
    materials: ['Platinum', '18k White Gold', '18k Rose Gold'],
    images: ['/images/earrings/earring-3.png', '/images/earrings/earring-1.png', '/images/earrings/earring-5.png'],
    description: 'A brilliant-cut diamond at the centre, surrounded by a halo of pavé-set stones that makes each earring appear dramatically larger. The Soleste Studs are designed to catch the light at every angle.',
    diamondMode: 'total-carat',
    caratIsPair: true,
    pricePerCarat: 4500,
  },
  'lumiere-chandeliers': {
    name: 'Lumière Chandeliers',
    subtitle: 'Diamond Chandelier Earrings',
    basePrice: 9200,
    materials: ['18k Yellow Gold', 'Platinum'],
    images: ['/images/earrings/earring-4.png', '/images/earrings/earring-2.png', '/images/earrings/earring-6.png'],
    description: 'Four tiers of diamonds radiate outward and downward from the ear in a dramatic chandelier form. Crafted in yellow gold, the Lumière Chandeliers are made for evenings that demand presence.',
    diamondMode: 'none',
  },
  'full-pave-hoops': {
    name: 'Full Pavé Hoops',
    subtitle: 'Diamond Hoop Earrings',
    basePrice: 6100,
    materials: ['Platinum', '18k White Gold', '18k Yellow Gold'],
    images: ['/images/earrings/earring-5.png', '/images/earrings/earring-3.png', '/images/earrings/earring-1.png'],
    description: 'A full circle of pavé-set brilliant-cut diamonds in platinum, creating a hoop that catches the light from every angle. The Full Pavé Hoops are the modern diamond hoop, elevated.',
    diamondMode: 'none',
  },
  'pear-elegance-drops': {
    name: 'Pear Elegance Drops',
    subtitle: 'Pear Diamond Drop Earrings',
    basePrice: 7400,
    materials: ['Platinum', '18k White Gold'],
    images: ['/images/earrings/earring-6.png', '/images/earrings/earring-2.png', '/images/earrings/earring-4.png'],
    description: 'A pear-shaped diamond in a claw setting suspends from a diamond-set bail in platinum. The elongated drop draws the eye downward, beautifully framing the face.',
    diamondMode: 'total-carat',
    caratIsPair: true,
    pricePerCarat: 4000,
  },
};

export const EARRING_FALLBACK = EARRING_PRODUCTS['brilliance-studs'];
