import 'server-only';

import { createAdminClient } from '@/lib/supabase/admin';
import { isPairEligible } from './eligibility';
import {
  parseDiamondPair,
  parseJewelleryStoneSlot,
  type DiamondPair,
  type JewelleryStoneSlot,
  type CreatePairInput,
  type CreateSlotInput,
} from './types';

// ── Pair admin operations ─────────────────────────────────────────────────────

/**
 * Insert a new diamond pair into the inventory.
 * pair_sku is auto-generated by the DB trigger if omitted.
 * Throws if either diamond_id does not exist, if both IDs are the same,
 * or if the DB uniqueness trigger fires (diamond already in an active pair).
 */
export async function createPair(input: CreatePairInput): Promise<DiamondPair> {
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from('diamond_pairs')
    .insert({
      diamond_id_a:       input.diamond_id_a,
      diamond_id_b:       input.diamond_id_b,
      shape:              input.shape,
      diamond_category:   input.diamond_category,
      colour_family:      input.colour_family   ?? null,
      colour:             input.colour           ?? null,
      clarity:            input.clarity          ?? null,
      colour_intensity:   input.colour_intensity ?? null,
      colour_description: input.colour_description ?? null,
      total_carat:        input.total_carat,
      carat_per_stone:    input.carat_per_stone  ?? null,
      pair_price_gbp:     input.pair_price_gbp,
      matching_notes:     input.matching_notes   ?? null,
      pair_sku:           input.pair_sku         ?? null,
    })
    .select('*')
    .single();

  if (error) throw new Error(`createPair: ${error.message}`);
  return parseDiamondPair(data);
}

/**
 * Validate pair integrity: fetch pair + constituent diamonds, check eligibility.
 * Returns an array of violation messages (empty = pair is valid).
 */
export async function validatePairIntegrity(
  pairId: string,
): Promise<string[]> {
  const supabase  = createAdminClient();
  const violations: string[] = [];

  const { data: pair, error } = await supabase
    .from('diamond_pairs')
    .select('*, diamond_a:diamonds!diamond_id_a(*), diamond_b:diamonds!diamond_id_b(*)')
    .eq('id', pairId)
    .single();

  if (error || !pair) {
    return [`Pair ${pairId} not found`];
  }

  const da = pair.diamond_a as Record<string, unknown>;
  const db = pair.diamond_b as Record<string, unknown>;

  if (!da) violations.push('diamond_a record missing');
  if (!db) violations.push('diamond_b record missing');

  if (da && db) {
    const eligible = isPairEligible({
      diamond_a: {
        cut:           da.cut as string,
        cut_grade:     da.cut_grade as string | null,
        polish:        da.polish as string | null,
        symmetry:      da.symmetry as string | null,
        fluorescence:  da.fluorescence as string | null,
        eclat_approved: da.eclat_approved as boolean,
        status:        da.status as 'available' | 'reserved' | 'sold',
        is_published:  da.is_published as boolean,
        diamond_category: da.diamond_category as 'white' | 'coloured',
        colour_family: da.colour_family as 'yellow' | 'pink' | null,
      },
      diamond_b: {
        cut:           db.cut as string,
        cut_grade:     db.cut_grade as string | null,
        polish:        db.polish as string | null,
        symmetry:      db.symmetry as string | null,
        fluorescence:  db.fluorescence as string | null,
        eclat_approved: db.eclat_approved as boolean,
        status:        db.status as 'available' | 'reserved' | 'sold',
        is_published:  db.is_published as boolean,
        diamond_category: db.diamond_category as 'white' | 'coloured',
        colour_family: db.colour_family as 'yellow' | 'pink' | null,
      },
      shape:            pair.shape as string,
      diamond_category: pair.diamond_category as 'white' | 'coloured',
      colour_family:    pair.colour_family as 'yellow' | 'pink' | null,
    });

    if (!eligible) {
      violations.push('One or both constituent diamonds do not meet Éclat quality standards');
    }

    if (da.status !== 'available' || db.status !== 'available') {
      violations.push('One or both constituent diamonds are not available');
    }
  }

  return violations;
}

/**
 * Mark pair as published (visible in catalogue).
 * Does not re-validate eligibility — call validatePairIntegrity first if needed.
 */
export async function publishPair(pairId: string): Promise<void> {
  const supabase = createAdminClient();
  const { error } = await supabase
    .from('diamond_pairs')
    .update({ is_published: true })
    .eq('id', pairId);
  if (error) throw new Error(`publishPair: ${error.message}`);
}

/**
 * Mark pair as unpublished (hidden from catalogue).
 *
 * Rejects with an error when the pair holds a valid (unexpired) reservation —
 * unpublishing a reserved pair would break constituent-diamond locking because
 * getActivePairDiamondIds would no longer see the pair (published=false), yet
 * the diamonds would remain reserved with no route back to available.
 *
 * This check is belt-and-suspenders; the database trigger
 * trg_prevent_unpublish_reserved (migration 0032) enforces the same rule.
 */
export async function unpublishPair(pairId: string): Promise<void> {
  const supabase = createAdminClient();
  const now      = new Date().toISOString();

  const { data: pair, error: fetchErr } = await supabase
    .from('diamond_pairs')
    .select('status, held_until')
    .eq('id', pairId)
    .single();

  if (fetchErr) throw new Error(`unpublishPair: ${fetchErr.message}`);

  if (pair?.status === 'reserved' && pair.held_until && pair.held_until > now) {
    throw new Error(
      `unpublishPair: cannot unpublish pair ${pairId} — active reservation expires at ${pair.held_until}`,
    );
  }

  const { error } = await supabase
    .from('diamond_pairs')
    .update({ is_published: false })
    .eq('id', pairId);
  if (error) throw new Error(`unpublishPair: ${error.message}`);
}

/**
 * Returns true when a diamond is a member of at least one active (non-sold) pair.
 * Used to gate admin deletion and individual-diamond reservation attempts.
 */
export async function isDiamondInActivePair(diamondId: string): Promise<boolean> {
  const supabase = createAdminClient();
  const { count, error } = await supabase
    .from('diamond_pairs')
    .select('id', { count: 'exact', head: true })
    .neq('status', 'sold')
    .or(`diamond_id_a.eq.${diamondId},diamond_id_b.eq.${diamondId}`);

  if (error) throw new Error(`isDiamondInActivePair: ${error.message}`);
  return (count ?? 0) > 0;
}

/**
 * Count available pairs compatible with a given slot (by raw constraint values).
 * Used to show "N pairs available" on the product page without loading full records.
 */
export async function countCompatiblePairsForSlot(opts: {
  shapes:           string[];
  min_carat:        number | null;
  max_carat:        number | null;
  categories:       string[];
  colour_families:  string[] | null;
}): Promise<number> {
  const supabase = createAdminClient();

  let q = supabase
    .from('diamond_pairs')
    .select('id', { count: 'exact', head: true })
    .eq('is_published', true)
    .eq('status', 'available');

  if (opts.shapes.length > 0)      q = q.in('shape', opts.shapes);
  if (opts.min_carat !== null)     q = q.gte('total_carat', opts.min_carat);
  if (opts.max_carat !== null)     q = q.lte('total_carat', opts.max_carat);
  if (opts.categories.length > 0)  q = q.in('diamond_category', opts.categories);
  if (opts.colour_families !== null && opts.colour_families.length > 0) {
    q = q.in('colour_family', opts.colour_families);
  }

  const { count, error } = await q;
  if (error) throw new Error(`countCompatiblePairsForSlot: ${error.message}`);
  return count ?? 0;
}

// ── Stone slot admin operations ───────────────────────────────────────────────

export async function createStoneSlot(input: CreateSlotInput): Promise<JewelleryStoneSlot> {
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from('jewellery_stone_slots')
    .insert({
      jewellery_product_id:       input.jewellery_product_id,
      slot_key:                   input.slot_key,
      label:                      input.label,
      display_order:              input.display_order              ?? 0,
      role:                       input.role,
      selection_mode:             input.selection_mode,
      required:                   input.required                   ?? true,
      quantity:                   input.quantity                   ?? 1,
      compatible_shapes:          input.compatible_shapes          ?? [],
      min_carat:                  input.min_carat                  ?? null,
      max_carat:                  input.max_carat                  ?? null,
      allowed_diamond_categories: input.allowed_diamond_categories ?? ['white', 'coloured'],
      allowed_colour_families:    input.allowed_colour_families    ?? null,
      price_mode:                 input.price_mode                 ?? 'selected_inventory',
      fixed_stone_description:    input.fixed_stone_description    ?? null,
    })
    .select('*')
    .single();

  if (error) throw new Error(`createStoneSlot: ${error.message}`);
  return parseJewelleryStoneSlot(data);
}

export async function listSlotsForProduct(
  jewelleryProductId: string,
): Promise<JewelleryStoneSlot[]> {
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from('jewellery_stone_slots')
    .select('*')
    .eq('jewellery_product_id', jewelleryProductId)
    .order('display_order', { ascending: true });

  if (error) throw new Error(`listSlotsForProduct: ${error.message}`);
  return (data ?? []).map(parseJewelleryStoneSlot);
}
